### ISSUE TITLE
Error stating backup directory path is invalid

### ISSUE THREAD

**Issue by sfregosi** [felipeam86/garpy#12]
Hi @felipeam86

Thanks for creating this and sharing it. I was able to install easily but am running into an error with actually trying to download data.  

OSError: [Errno 22] Invalid argument: 'c:\\users\\selene\\downloads\\2021-04-28T12:52:38+00:00_6687511285.fit'

It states this error no matter what I specify as the backup directory or what other options I do or do not include. Any thoughts? 

Thanks,
Selene
![garpy_Screenshot 2021-04-28 131646](https://user-images.githubusercontent.com/22456126/116446333-d887ce80-a824-11eb-94c7-8511e0e5fa52.png)

**Comment by felipeam86** [comment]
Hi @sfregosi 

Thank you for giving garpy a try and reporting the bug.

1. Is this the first time you try garpy or have you successfully used it before?
2. Can you please do `garpy download` without any arguments and share the screenshot?

I'll find some time soon to switch to Windows and give it a try on my side.

Cheers

**Comment by sfregosi** [comment]
1. This is the first time I've tried it. I also tried installing/running on my desktop rather than my laptop and no luck there...but both are Windows. I don't have access to a non-windows machine, unfortunately. 
2. Attached the output just running `garpy download` 

I searched that error and I think it might have to do with the file name 2021-04-28T12:52:38 containing ":" in the filename? I'm ok with installing and running things in python but relatively new to it. 

![image](https://user-images.githubusercontent.com/22456126/116460138-b26a2a80-a834-11eb-9243-1b6c7a8f08ed.png)

**Comment by felipeam86** [comment]
@sfregosi thanks for that. I have just run the test suite on a windows machine and they are failing with the same error you are getting.

This has nothing to do with your Python skills, I guess my code has never worked in Windows and you are the first brave Windows user to report that. Thank you very much! I'll take a look at this as soon as I get some time this week and try to make the code compatible with Windows.

**Comment by sfregosi** [comment]
Hi @felipeam86, 
Happy to be the first brave Windows user! Thanks for looking into it and I look forward to see what you find. 
Selene

**Comment by felipeam86** [comment]
Found the problem! pull request #13 will fix this. I will make a new release before the end of the week.

Thanks again for reporting, now the code is compatible with Linux, Mac and Windows!!!!

**Comment by sfregosi** [comment]
Hi @felipeam86 I was able to install the new version, but now I'm getting an authentication error (I swear I'm typing in my password right! Tested it with -u username -p password to be sure...just don't want to post that screenshot here). Any thoughts?
Thanks! 
![image](https://user-images.githubusercontent.com/22456126/117736848-9e281500-b1c6-11eb-84c5-f8d61222d6b6.png)

**Comment by felipeam86** [comment]
Hi @sfregosi 

Yes, this is a new issue. Garmin has strengthened their anti-bot measures. I already find a fix. I'll do a release with the fix asap

**Comment by felipeam86** [comment]
Ok!! @sfregosi I did a new release. Can you please run pip install -U garpy and try again?

This time should work :crossed_fingers: 

Thanks for reporting the issues

**Comment by Dave-DigiMim** [comment]
Thanks also fixed  my issue!

**Comment by sfregosi** [comment]
Hi @felipeam86 I'm still running into an authentication error :(

![image](https://user-images.githubusercontent.com/22456126/118669689-f57c4580-b7c3-11eb-809a-6948089503c8.png)

@Dave-DigiMim You got it working on windows? Would you mind sharing a screenshot of your steps? Thanks!

**Comment by felipeam86** [comment]
Hi @sfregosi 

Garmin has yet again strengthened their security and are blocking the authentication procedure. See issue #19 for a follow up on a resolution.

This has nothing to do with Windows :)

Thanks again for your interest on `garpy`

**Comment by felipeam86** [comment]
Ok, @sfregosi you chose the worst moment to start using `garpy`, sorry for that. Garmin is getting strict !!!

New release with a fix. Hopefully this fix will be more robust

Can you please run `pip install -U garpy` and try again?
