### ISSUE TITLE
Credential issues again

### ISSUE THREAD

**Issue by Dave-DigiMim** [felipeam86/garpy#27]
Hi
Looks like the end of the road..
<h1>Access denied</h1>
  <p>This website is using a security service to protect itself from online attacks.</p>
  <ul class="cferror_details">
    <li>Ray ID: 6e6bbe79ec1f4f87</li>
    <li>Timestamp: 2022-03-04 15:46:19 UTC</li>
    <li>Your IP address: 66.251.179.200</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: sso.garmin.com/sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern </li>
    <li>Error reference number: 1020</li>
    <li>Server ID: FL_45F48</li>
    <li>User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36</li>
  </ul>

**Comment by felipeam86** [comment]
Hi @Dave-DigiMim

Thanks for reporting your issue!

What version of garpy are you using?

**Comment by Dave-DigiMim** [comment]
I upgraded to the latest. 3.0.6 i think. One later than on pip install. My last update was 31 jan.Sent from my Galaxy
-------- Original message --------From: Felipe Aguirre Martinez ***@***.***> Date: 2022/03/04  22:59  (GMT+02:00) To: felipeam86/garpy ***@***.***> Cc: Dave Ingram ***@***.***>, Mention ***@***.***> Subject: Re: [felipeam86/garpy] Credential issues again (Issue #27) 
Hi @Dave-DigiMim
Thanks for reporting your issue!
What version of garpy are you using?

**Comment by Dave-DigiMim** [comment]
Felipe

This is my full auth_response.txt form client.py line 142

 

Regards

**Comment by Dave-DigiMim** [comment]
https://github.com/Pythe1337N/garmin-connect/issues/26

Likenttt <https://github.com/Likenttt>  commented on Jan 7 <https://github.com/Pythe1337N/garmin-connect/issues/26#issuecomment-1007152656>  • 

edited 


I have tried the repo garminexport <https://github.com/petergardfjall/garminexport> , and it worked for me.
I found the procedure was a little different from that you used.
That repo's login authentication will do like below.

1.	Get sso.garmin.com/sso/signin as a html text
2.	Use a regular expression to search the csrf token from text in 1 and add the csrf token as _csrf kv in data posted later
3.	Post and retrieve the response as html
4.	Use a regular expression to search the auth_ticket from 3
5.	Get the auth_ticket url(claim the ticket)
6.	Get connect.garmin.com/modern to finish the login process.

 

Regards

**Comment by felipeam86** [comment]
I have just tested and it is working without an issue for me. 

Garmin has strengthened their security measures and it's not clear for me why it sometimes work and sometimes doesn't...

Maybe if you try login in first on the browser before launching garpy? I've heard this has worked for some people

Sorry for the inconvenience!

**Comment by Dave-DigiMim** [comment]
I  tried gcdown  if I try 2 quickly it blocks the second one same error as garpy . After waiting 5 mins it works.  Garpy has not worked since 31 jan.  I run unattended on a raspberry pi, so difficult to login first.  Sent from my Galaxy
-------- Original message --------From: Felipe Aguirre Martinez ***@***.***> Date: 2022/03/05  18:06  (GMT+02:00) To: felipeam86/garpy ***@***.***> Cc: Dave Ingram ***@***.***>, Mention ***@***.***> Subject: Re: [felipeam86/garpy] Credential issues again (Issue #27) 
I have just tested and it is working without an issue for me.
Garmin has strengthened their security measures and it's not clear for me why it sometimes work and sometimes doesn't...
Maybe if you try login in first on the browser before launching garpy? I've heard this has worked for some people
Sorry for the inconvenience!

**Comment by Dave-DigiMim** [comment]
This is my attempted log in

I saved the authresponse to the attached file

Maybe you could try my login



 

Regards
