### ISSUE TITLE
"mkl" == "kml"?

### ISSUE THREAD

**Issue by krissen** [felipeam86/garpy#36]
Hi,

Garpy supports formats `'original', 'mkl', 'details', 'gpx', 'summary', 'tcx'`. However, `mkl` is a `KML` file and surely should be named as such as well?

Also, `README.md` could be updated with the available formats.

Currently "`mkl`" is missing.

```
Options:
  -f, --formats [tcx|gpx|original|summary|fit|details]
                                  Which formats to download. The flag can be
                                  used several times, e.g. '-f original -f
                                  gpx'
```

`garpy download --help` reports

```
Options:
  -f, --formats [tcx|gpx|mkl|original|fit|summary|details]
                                  Which formats to download. The flag can be
                                  used several times, e.g. '-f original -f
                                  gpx'
```

Also, is there a difference between `original` and `fit`?

**Comment by felipeprediktia** [comment]
Hi @krissen thank you for reporting this. You are right, it should be KML. I have fixed this and made a new release. Please update to version 0.3.8.

In my case, **original** and **fit** are always the same. My intuition is that Garmin saves whatever format you use to upload the activity as the original. Given that I only upload activities through my Garmin devices, it is always **fit'** for me.

**Comment by felipeam86** [comment]
Hi @krissen thank you for reporting this. You are right, it should be KML. I have fixed this and made a new release. Please update to version 0.3.8.

In my case, **original** and **fit** are always the same. My intuition is that Garmin saves whatever format you use to upload the activity as the **original**. Given that I only upload activities through my Garmin devices, it is always **fit** for me.
